const BE_INSPIRED = [
  "Let's circle back to that thought while we pivot to the next big idea!",
  "Remember, it's not just a meeting; it's a ‘value-generating brainstorming session!'",
  "Our team spirit is as high as our coffee consumption—let's keep it brewing!",
  "This week's KPI: finding out how many buzzwords we can fit in one meeting.",
  "Scrum meetings: where we all sit around discussing how to avoid actual work.",
  "If it's not on the project plan, does it even exist? Asking for a friend.",
  "Let's synergize our deliverables and optimize our paradigms, whatever that means!",
  "We value innovation—especially when it's someone else's idea from last year.",
  "Don't worry, we'll get to 'inbox zero' after we finish these 18 new emails!",
  "This quarter's goal: make 'synergy' the most used word in the office.",
  "We're all about agile practices—especially when it comes to dodging accountability.",
  "New initiative: 'freedom to fail'—as long as you don't let anyone notice.",
  "Don't forget to leverage your strengths while we redefine 'best practices'!",
  "We're on a journey to reach our benchmarks… but first, let's have another meeting!",
  "Our corporate culture? It's like a family reunion, just with more awkward silences.",
  "Don't just be a team player—be a team superstar! Shine bright like a KPI.",
  "We're empowering you to take initiative! Just don't forget to clear it with management.",
  "Today's agenda: discuss yesterday's agenda, but only if it's still relevant.",
  "Let's disrupt the market with our cutting-edge ideas—once we figure out what they are.",
  "Remember, every setback is just a 'learning opportunity' in disguise!",
  "Lets synergize our efforts and leverage our core competencies in this brainstorm session.",
  "New team motto: work smarter, not harder, but mostly harder for fun.",
  "Remember, your opinions are valued as long as they match the company line.",
  "Lets take this offline and then forget about it altogether.",
  "Our new project is so agile, it might just leap off the charts.",
  "Dont worry, the meeting could have been an email, but we like to socialize.",
  "We are all about open communication, as long as its behind closed doors.",
  "Just because its on the calendar doesnt mean it actually matters.",
  "Our strategy is simple: more meetings equal more success, right?",
  "We are all about continuous improvement until we get tired of improving.",
  "Remember, theres no I in team, but there is in initiative.",
  "We value creativity, especially when it comes to filling out expense reports.",
  "Lets think outside the box while staying comfortably inside our comfort zone.",
  "Our corporate mission is to generate synergy without actually doing anything.",
  "We encourage proactive engagement, as long as it doesnt disrupt our coffee breaks.",
  "Your feedback is crucial just not crucial enough to change anything.",
  "Lets optimize our workflows while we redefine the meaning of productivity.",
  "Dont forget to pivot quickly, even if were not sure what were pivoting to.",
  "We promote a culture of accountability just as long as you dont hold me accountable.",
  "This quarter, lets aim for excellence while we settle for mediocrity.",
];

export { BE_INSPIRED };
